"""add_photos_urls_to_report_on_goods

Revision ID: 057c40fe6222
Revises: f58f0700342a
Create Date: 2025-11-14 11:17:19.646176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057c40fe6222'
down_revision: Union[str, None] = 'f58f0700342a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reportongoods', sa.Column('photos_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reportongoods', 'photos_urls')
    # ### end Alembic commands ###
