"""replace_primehill_with_yandex_pay_qr

Revision ID: 2f066241973f
Revises: 057c40fe6222
Create Date: 2026-04-21 17:29:06.783269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f066241973f'
down_revision: Union[str, None] = '057c40fe6222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_reports', sa.Column('yandex_pay_qr', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.drop_column('shift_reports', 'primehill')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_reports', sa.Column('primehill', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.drop_column('shift_reports', 'yandex_pay_qr')
    # ### end Alembic commands ###
