"""new model

Revision ID: 41383f19dc55
Revises: 91a37f3e1550
Create Date: 2025-09-06 17:36:38.652871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41383f19dc55'
down_revision: Union[str, None] = '91a37f3e1550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writeofftransfer', sa.Column('location_to', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writeofftransfer', 'location_to')
    # ### end Alembic commands ###
