"""add_receipt_photo_path_to_shift_reports

Revision ID: f58f0700342a
Revises: f4763f825583
Create Date: 2025-11-12 19:47:02.585961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58f0700342a'
down_revision: Union[str, None] = 'f4763f825583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_reports', sa.Column('receipt_photo_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_reports', 'receipt_photo_path')
    # ### end Alembic commands ###
